# If only a header file is modified, need to run "wmake clean" to recompile.
# Need to run "wmake clean" before compiling for different target (16/32-bit).

OBJECTS = zmenu.obj int.obj position.obj

LD = wlink

.EXTENSIONS:
.EXTENSIONS: .exe .obj .c

# Build without .exe extension
zmenu: zmenu.exe .SYMBOLIC
    @%null

zmenu32: zmenu32.exe .SYMBOLIC
    @%null

zmenu.exe: env16 $(OBJECTS)
	%make zmenu.lnk
	$(LD) @zmenu.lnk

zmenu32.exe: env32 $(OBJECTS)
	%make zmenu.lnk
	$(LD) @zmenu.lnk

env16: .SYMBOLIC
	set NAME=zmenu
	set CC = wcc
	set CFLAGS = -zq -mc -oh
	set SYSTEM = dos

env32: .SYMBOLIC
	set NAME=zmenu32
	set CC = wcc386
	set CFLAGS = -zq -oh
	set SYSTEM = dos4g

zmenu.lnk:
	%create $@
	%append $@ NAME $(%NAME)
	%append $@ SYSTEM $(%SYSTEM)
	%append $@ FILE {$(OBJECTS)}

.ERASE
.c.obj:
	$(%CC) -fo=$@ $(%CFLAGS) $<

clean: .SYMBOLIC
	@if exist *.LNK del *.LNK
	@if exist *.OBJ del *.OBJ
	@if exist *.EXE del *.EXE
	@if exist *.ERR del *.ERR
